name: Build & Export Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 构建镜像
      - name: Build Docker image
        run: docker build -t dockermy .

      # 导出镜像为文件
      - name: Export Docker image
        run: docker save -o dockermy.tar dockermy

      # 上传为构建产物（你可以下载）
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dockermy-image
          path: dockermy.tar
