name: Build Docker Image Only

# 提交代码时自动构建
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 只构建，不登录、不推送
      - name: Build Docker image
        run: |
          docker build -t dockermy .
